spring:
  data:
    mongodb:
      uri: ${BILIOB_MONGO_URL}
    redis:
      repositories:
        enabled: false
  redis:
    lettuce:
      pool:
        max-active: -1
        max-idle: 8
        min-idle: 0
        max-wait: -1
      shutdown-timeout: 30000
    host: ${BILIOB_REDIS_URL}
    port: ${BILIOB_REDIS_PORT}
    password: ${BILIOB_REDIS_PASSWD}
    timeout: 30000
  mail:
    host: smtp.biliob.com
    password: ${BILIOB_MAIL_PASSWORD}
    username: jannchie@biliob.com
    port: 465
    default-encoding: UTF-8
    properties:
      mail.smtp.socketFactory.fallback: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
      mail.smtp.ssl:
        enable: true
server:
  port: ${BILIOB_BACKEND_PORT}
